apiVersion: v1
kind: ConfigMap
metadata:
  name: payment
  namespace: roboshop
data:
  CART_HOST: "cart"
  CART_PORT: "8080"
  USER_HOST: "user"
  USER_PORT: "8080"
  AMQP_HOST: "rabbitmq"
  AMQP_USER: "roboshop"
  AMQP_PASS: "roboshop123"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: roboshop
  labels:
    project: roboshop
    component: payment
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      component: payment
      tier: backend
  template:
    metadata:
      labels:
        project: roboshop
        component: payment
        tier: backend
    spec:
      containers:
      - name: payment
        image: aravind527/payment:v1
        imagePullPolicy: Always
        resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
        envFrom:
        - configMapRef:
            name: payment
        readinessProbe:
            httpGet:
              path: /health
              port: 8080 
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 3
        livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: roboshop
spec:
  selector:
    project: roboshop
    component: payment
    tier: backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080 
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
 - name: payment-hpa
   namespace: roboshop
   labels:
    project: roboshop
    component: payment
    tier: backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: payment   #deployment name
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
           type: Utilization
           averageUtilization: 25