apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping
  namespace: roboshop
data:
 CART_ENDPOINT: "cart:8080"
 DB_HOST: "mysql"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  namespace: roboshop
  labels:
    project: roboshop
    component: shipping
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      component: shipping
      tier: backend
  template:
    metadata:
      labels:
        project: roboshop
        component: shipping
        tier: backend
    spec:
      containers:
      - name: shipping
        image: aravind527/shipping:v1
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "400m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        envFrom:
        - configMapRef:
           name: shipping
        readinessProbe:
           httpGet:
            path: /health
            port: 8080 
           failureThreshold: 3
           periodSeconds: 15
           initialDelaySeconds: 60
        livenessProbe:
           httpGet:
            path: /health
            port: 8080
           failureThreshold: 3
           periodSeconds: 15
           initialDelaySeconds: 60

---
apiVersion: v1
kind: Service
metadata:
  name: shipping
  namespace: roboshop
spec:
  selector:
    projrect: roboshop
    component: shipping
    tier: backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080 
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
 - name: shipping-hpa
   namespace: roboshop
   labels:
    project: roboshop
    component: shipping
    tier: backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shipping   #deployment name
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
           type: Utilization
           averageUtilization: 25