#service, headless service, statefulset,pvc dynamic with sc
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: roboshop
spec: 
  selector:
    project: roboshop
    component: redis
    environment: dev
    tier: db
  ports:
   - protocol: TCP
     port: 6379
     targetPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-headless
  namespace: roboshop
spec: 
  clusterIP: None
  selector:
    project: roboshop
    component: redis
    environment: dev
    tier: db
  ports:
   - protocol: TCP
     port: 6379
     targetPort: 6379
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: roboshop
spec:
  selector:
    matchLabels:
       project: roboshop
       component: redis
       environment: dev
       tier: db  
  serviceName: "redis-headless"   #this should be head less service name
  replicas: 2
  template:
    metadata:
      labels:
        project: roboshop
        component: redis
        environment: dev
        tier: db  # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: redis
        image: aravind527/redis:v1
        volumeMounts:
        - name: redis
          mountPath: /data

# this is pvc
  volumeClaimTemplates:
  - metadata:
      name: redis
    spec:
      accessModes: [ "ReadWriteOnce"]
      storageClassName: "roboshop-ebs"
      resources:
        requests:
          storage: 1Gi
     
 